[package]
name = 'solution4'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies]
simple-swap = { local = '../ctfmovement-4' }

[addresses]
solution = '_'
