[package]
name = 'solution2'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies]
hello_move = { local = '../ctfmovement-2' }

[addresses]
solution = '_'